### ISSUE TITLE
字典汉化无效

### ISSUE THREAD

**Issue by trlaitioer** [Future-R/ErbParserForTranslate#1]
## 设置
ERA为[EraFL](https://gitgud.io/kom1t/erafl/-/tree/master?ref_type=heads)的main分支，最后的commit的SHA是6211826668949f7ab99d5f608730fb5ac61067f9
使用的ErbParser版本是Debug0.41

## 具体
具体表现是，使用ErbParser正常提取到json格式的PT字典
但是没办法使用翻译后的PT字典汉化游戏

## 复现方法
提取出PT字典后，修改任意词条的translation
使用字典汉化游戏，发现游戏未被翻译

**Comment by Future-R** [comment]
只修改"translation"是不够的，还需要修改"stage": 1，以此标记这个词条是已翻译状态。
推荐把PT字典上传到paratranz.cn进行修改，可以设置项目为隐私。

**Comment by trlaitioer** [comment]
> 只修改"translation"是不够的，还需要修改"stage": 1，以此标记这个词条是已翻译状态。 推荐把PT字典上传到paratranz.cn进行修改，可以设置项目为隐私。

工具提取出的JSON没有stage这个key
README也没提
我用本地LLM翻译的，翻译后的也没有stage

https://github.com/Future-R/ErbParserForTranslate/blob/228bdc4496e43f0418c561370748ce01da12594b/ErbParserDotNet/Tools.cs#L246
感觉其实没必要判stage

**Comment by Future-R** [comment]
从平台上下载后，就会自动添加stage。
我这里是觉得没必要，所以在提取的时候没添加stage属性，这样还能减小上传的数据量。
stage对于多人协作翻译来说是很有必要的，可以标记这个词条当前属于未翻译、已翻译、有疑问、一次校对、二次校对等状态。
如果需要的话，我可以添加一项设置，在提取时添加一行"stage": 0。

**Comment by trlaitioer** [comment]
> 从平台上下载后，就会自动添加stage。 我这里是觉得没必要，所以在提取的时候没添加stage属性，这样还能减小上传的数据量。 stage对于多人协作翻译来说是很有必要的，可以标记这个词条当前属于未翻译、已翻译、有疑问、一次校对、二次校对等状态。 如果需要的话，我可以添加一项设置，在提取时添加一行"stage": 0。

我觉得应该添加的设置是忽略stage
我看了一下我用的[AiNiee](https://github.com/NEKOparapa/AiNiee)，它没有对stage做任何操作

https://github.com/NEKOparapa/AiNiee/blob/0c2dbc89ed853ee87b7b1dfecf8e00f2d65fc129/Module_Folders/File_Reader/File1.py#L48

**Comment by Future-R** [comment]
啊！如果用的是AiNiee的话，其实可以用
[ 4] - 将PT字典转换成MTool字典
这个指令导出的MTool字典是可以被AiNee直接处理的。
AiNee处理完后，再使用
[ 5] - 将MTool机翻导入PT字典
就可以了。

**Comment by trlaitioer** [comment]
> 啊！如果用的是AiNiee的话，其实可以用 [ 4] - 将PT字典转换成MTool字典 这个指令导出的MTool字典是可以被AiNee直接处理的。 AiNee处理完后，再使用 [ 5] - 将MTool机翻导入PT字典 就可以了。

但是AiNiee可以直接处理PT字典啊……
