### ISSUE TITLE
它直接把游戏erb目录干没了，害怕

### ISSUE THREAD

**Issue by KuroPeach** [Future-R/ErbParserForTranslate#2]
尝试的提取eratohoYMAEM，报个错闪退，然后被搞没了，害怕

**Comment by Future-R** [comment]
啊？你是不是把字典工具放在游戏目录里了？

**Comment by KuroPeach** [comment]
并没有，我是按照提示把游戏目录拖上去的，不过后面没事了，我重新下载了一遍游戏，这次倒是提取出来了。这也没个日志，不清楚当时发生了啥，游戏里的CSV和ERB目录直接没了。或许可以考虑加个日志功能。：）

**Comment by Future-R** [comment]
没见过这个问题，我只会清理工具程序同目录下的文件；
至于汉化的目标文件，是不会清理，而是原地写入的，代码也是开源可查的。

**Comment by KuroPeach** [comment]
但它确实把游戏里的那俩目录搞没了，而且工具和游戏没在一起，游戏在Galgame目录，工具在Download目录，就很震惊，直接没了
